// Generated by: spec-data-model skill
// Source spec: .sdd/specs/005-review-spec-completeness.spec.md, Section 7
// Target language: TypeScript
// DO NOT EDIT MANUALLY -- regenerated on spec revision

// --- Section 7.1: Completeness Finding ---

export type CompletenessFindingSeverity = 'HIGH' | 'MEDIUM' | 'LOW';

export type CompletenessFindingCategory =
  | 'obligation-language'
  | 'error-behavior'
  | 'data-model'
  | 'api-contract'
  | 'state-machine'
  | 'traceability'
  | 'integration'
  | 'ambiguity'
  | 'artifact-consistency'
  | 'security';

export interface CompletenessFinding {
  /** Unique finding identifier, format: SPEC-COMP-XXX */
  id: string;
  /** Impact level */
  severity: CompletenessFindingSeverity;
  /** Finding type */
  category: CompletenessFindingCategory;
  /** Where in the spec, e.g. "Section N, FR-XXX" or entity name */
  location: string;
  /** What is wrong. 1-500 chars. */
  issue: string;
  /** How to fix. 1-500 chars. */
  recommendation: string;
}

// --- Section 7.2: Contract Finding ---

export type ContractFindingCategory =
  | 'interface-mismatch'
  | 'schema-mismatch'
  | 'api-mismatch'
  | 'state-mismatch'
  | 'error-mismatch';

export interface ContractFinding {
  /** Unique finding identifier, format: SPEC-CONTRACT-XXX */
  id: string;
  /** Impact level */
  severity: CompletenessFindingSeverity;
  /** Contract check type */
  category: ContractFindingCategory;
  /** Contract file path */
  contract_file: string;
  /** Implementation file path and line, format: path:line */
  impl_file: string;
  /** What the contract defines */
  expected: string;
  /** What the code implements */
  actual: string;
  /** How to fix. 1-500 chars. */
  recommendation: string;
}

// --- Section 7.3: Verdict ---

export type VerdictResult = 'PASS' | 'FAIL';

export interface Verdict {
  /** Overall assessment */
  result: VerdictResult;
  /** Number of HIGH findings, >= 0 */
  high_count: number;
  /** Number of MEDIUM findings, >= 0 */
  medium_count: number;
  /** Number of LOW findings, >= 0 */
  low_count: number;
}
