// Generated by: spec-data-model skill
// Source spec: .sdd/specs/008-orchestrator-v2.spec.md, Section 7
// Target language: TypeScript
// DO NOT EDIT MANUALLY -- regenerated on spec revision

/**
 * Valid pipeline stages for the Orchestrator state machine.
 */
export type PipelineStage =
  | "idle"
  | "ideation"
  | "specification"
  | "planning"
  | "implementation"
  | "review"
  | "documentation"
  | "complete";

/**
 * Result of the last agent invocation.
 */
export type AgentResult = "success" | "failed" | "escalated" | null;

/**
 * An entry in the error log recording a single agent failure.
 */
export interface ErrorEntry {
  /** Name of the agent that failed. */
  agent: string;
  /** WP identifier (e.g., "WP01") or null if not WP-scoped. */
  wp: string | null;
  /** Human-readable summary of the error, 1-500 characters. */
  error_summary: string;
  /** ISO 8601 timestamp of when the error occurred. */
  timestamp: string;
}

/**
 * The persistent pipeline state stored as YAML frontmatter in .sdd/state.md.
 */
export interface PipelineState {
  /** Current pipeline stage. */
  pipeline_stage: PipelineStage;
  /** Path to the active spec file, or null. */
  current_spec: string | null;
  /** Current WP identifier (e.g., "WP01"), or null. */
  current_wp: string | null;
  /** Name of the last agent invoked, or null. */
  last_agent: string | null;
  /** Result of the last agent invocation. */
  last_result: AgentResult;
  /** Number of retries attempted for the current agent (0-2). */
  retry_count: number;
  /** Array of error entries, max 50 (oldest pruned). */
  error_log: ErrorEntry[];
  /** ISO 8601 timestamp of the last state update. */
  updated_at: string;
}

/**
 * WP lane values managed by specialist agents.
 */
export type WPLane = "planned" | "doing" | "for_review" | "to_do" | "done";

/**
 * WP frontmatter fields relevant to the Orchestrator's decision logic.
 */
export interface WPFrontmatter {
  /** Current lane/status of the WP. */
  lane: WPLane;
  /** WP identifier (e.g., "WP01"). */
  wp: string;
  /** WP title. */
  title: string;
  /** List of WP identifiers this WP depends on. */
  depends_on: string[];
}
