// Generated by: spec-data-model skill
// Source spec: .sdd/specs/008-orchestrator-v2.spec.md, Section 7.0
// Target language: TypeScript
// DO NOT EDIT MANUALLY -- regenerated on spec revision

import type { PipelineStage } from "./data-models";

/**
 * Valid transitions for the pipeline_stage state machine.
 * Key = current stage, value = set of stages reachable from it.
 */
export const VALID_PIPELINE_TRANSITIONS: Record<PipelineStage, ReadonlySet<PipelineStage>> = {
  idle: new Set<PipelineStage>(["ideation", "specification", "planning", "implementation"]),
  ideation: new Set<PipelineStage>(["specification"]),
  specification: new Set<PipelineStage>(["planning"]),
  planning: new Set<PipelineStage>(["implementation"]),
  implementation: new Set<PipelineStage>(["review", "complete"]),
  review: new Set<PipelineStage>(["documentation", "implementation"]),
  documentation: new Set<PipelineStage>(["implementation", "complete"]),
  complete: new Set<PipelineStage>([]),
};

/**
 * Checks whether a pipeline_stage transition is valid.
 * Returns true if the transition from `from` to `to` is allowed.
 */
export function isValidTransition(from: PipelineStage, to: PipelineStage): boolean {
  return VALID_PIPELINE_TRANSITIONS[from].has(to);
}

/**
 * Maximum retry count before escalation.
 */
export const MAX_RETRY_COUNT = 2;

/**
 * Maximum review cycles before escalation (review returning lane=to_do).
 */
export const MAX_REVIEW_CYCLES = 3;

/**
 * Maximum error log entries (oldest pruned when exceeded).
 */
export const MAX_ERROR_LOG_ENTRIES = 50;

/**
 * Decision table: maps conditions to the agent to delegate to and the resulting pipeline stage.
 */
export interface DecisionEntry {
  condition: string;
  action: string;
  delegateTo: string | null;
  stateAfter: PipelineStage;
}

export const DECISION_TABLE: readonly DecisionEntry[] = [
  { condition: "No ideas, no specs, no plans", action: "Ask user for intent", delegateTo: null, stateAfter: "idle" },
  { condition: "Brief exists without matching spec", action: "Turn brief into spec", delegateTo: "Spec Architect", stateAfter: "specification" },
  { condition: "Spec exists without work packages", action: "Decompose spec into WPs", delegateTo: "Planner", stateAfter: "planning" },
  { condition: "WP with lane=planned, dependencies met", action: "Implement WP", delegateTo: "Coder", stateAfter: "implementation" },
  { condition: "WP with lane=for_review", action: "Review WP", delegateTo: "Review Coordinator", stateAfter: "review" },
  { condition: "WP with lane=done, not yet documented", action: "Generate docs", delegateTo: "Docs Agent", stateAfter: "documentation" },
  { condition: "WP with lane=to_do (changes requested)", action: "Fix feedback", delegateTo: "Coder", stateAfter: "implementation" },
  { condition: "All WPs lane=done AND documented", action: "Pipeline complete", delegateTo: null, stateAfter: "complete" },
  { condition: "All MVP WPs done, non-MVP remain", action: "Ask user to continue", delegateTo: null, stateAfter: "idle" },
  { condition: "Agent failure, retry_count < max", action: "Retry failed agent", delegateTo: "Same agent", stateAfter: "idle" },
  { condition: "Agent failure, retry_count >= max", action: "Escalate to user", delegateTo: null, stateAfter: "idle" },
] as const;
