// Generated by: spec-data-model skill
// Source spec: .sdd/specs/006-handoff-schemas-patterns.spec.md, Section 7
// Target language: TypeScript
// DO NOT EDIT MANUALLY -- regenerated on spec revision

// --- Handoff Schema (Section 7.1) ---

export interface ArtifactValidation {
  /** Field name to check (e.g., "Status") */
  field?: string;
  /** Expected field value */
  value?: string;
  /** Whether the artifact must exist */
  exists?: boolean;
  /** Minimum number of files (for directory globs) */
  min_files?: number;
}

export interface ArtifactSpec {
  /** File path or glob pattern (e.g., ".sdd/specs/{NNN}-{name}.spec.md") */
  path: string;
  /** Validation rules for this artifact */
  validation: ArtifactValidation[];
}

export interface StateCondition {
  /** Boolean condition expression (e.g., "spec.status == 'Validated'") */
  condition: string;
  /** Error message if condition is not met */
  error: string;
}

export interface ContextField {
  /** Field name (e.g., "spec_path") */
  name: string;
  /** Field type (e.g., "string") */
  type: string;
  /** Whether the field is required in the handoff prompt */
  required: boolean;
  /** Human-readable description of the field */
  description: string;
}

export type ValidationCheckType = "file_exists" | "field_value";

export interface ValidationRule {
  /** Type of validation check */
  check: ValidationCheckType;
  /** Context field to validate against */
  target: string;
  /** Field name within the target (for field_value checks) */
  field?: string;
  /** Expected value (for field_value checks) */
  expected?: string;
  /** Error message if check fails */
  error: string;
}

export interface HandoffSchema {
  /** Schema format version (e.g., "handoff/v1") */
  schema: string;
  /** Name of the producing agent */
  source_agent: string;
  /** Name of the consuming agent */
  target_agent: string;
  /** Purpose of this handoff, 1-200 chars */
  description: string;
  /** Files that must exist before handoff, min 1 */
  required_artifacts: ArtifactSpec[];
  /** State conditions that must be true (optional) */
  required_state?: StateCondition[];
  /** Key-value pairs required in the handoff prompt, min 1 */
  context_fields: ContextField[];
  /** Additional validation checks (optional) */
  validation_rules?: ValidationRule[];
}

// --- Pattern Entry (Section 7.2) ---

export type PatternStatus = "active" | "retired" | "superseded";

export type PatternDomain = "SPEC" | "PLAN" | "CODE" | "DOC";

export interface PatternEntry {
  /** Unique pattern ID in format PAT-{DOMAIN}-XXX */
  id: string;
  /** Brief description, 1-100 chars */
  title: string;
  /** Current lifecycle state */
  status: PatternStatus;
  /** Date pattern was created, YYYY-MM-DD */
  added: string;
  /** Origin reference (e.g., "Review of WP01" or "manual") */
  source: string;
  /** Symptom description, 1-500 chars */
  trigger: string;
  /** How to avoid the pattern, 1-500 chars */
  prevention: string;
  /** Concrete instance of the pattern and its fix (optional) */
  example?: string;
  /** Date pattern was retired (set when status changes to "retired") */
  retired?: string;
}
