// Generated by: spec-data-model skill
// Source spec: .sdd/specs/006-handoff-schemas-patterns.spec.md, Section 7
// Target language: TypeScript
// DO NOT EDIT MANUALLY -- regenerated on spec revision

import type { PatternStatus } from "./data-models";

// --- Pattern Status Transitions (FR-013, FR-014) ---

/**
 * Valid state transitions for PatternEntry.status:
 *
 *   active --> retired      (FR-014: not triggered in 10 consecutive reviews)
 *   active --> superseded   (manually replaced by a newer pattern)
 *
 * "retired" and "superseded" are terminal states.
 */

export const PATTERN_STATUS_TRANSITIONS: Record<PatternStatus, PatternStatus[]> = {
  active: ["retired", "superseded"],
  retired: [],
  superseded: [],
};

export function isValidPatternTransition(
  from: PatternStatus,
  to: PatternStatus
): boolean {
  return PATTERN_STATUS_TRANSITIONS[from].includes(to);
}
