// Generated by: spec-data-model skill
// Source spec: .sdd/specs/009-research-skill-ideation.spec.md, Section 7
// Target language: TypeScript
// DO NOT EDIT MANUALLY -- regenerated on spec revision

// --- Research Request (Section 7.1) ---

export type ResearchScope = "web" | "codebase" | "packages";

export interface ResearchRequest {
  /** The subject to research. 1-200 characters. */
  topic: string;
  /** Research scopes to execute. At least 1 element. */
  scope: [ResearchScope, ...ResearchScope[]];
  /** Specific questions to answer. 1-10 items, each 1-500 characters. */
  questions: [string, ...string[]];
  /** Path where findings SHALL be written. */
  output_file: string;
}

// --- Research Output (Section 7.2) ---

export interface ResearchSource {
  title: string;
  url: string;
  date_consulted: string; // ISO 8601 date
}

export interface QuestionAnswer {
  question: string;
  answer: string;
  sources: ResearchSource[];
}

export interface CompetitiveSolution {
  solution: string;
  approach: string;
  strengths: string;
  weaknesses: string;
  source: ResearchSource;
}

export interface TechnologyEvaluation {
  technology: string;
  version: string;
  status: string;
  license: string;
  last_updated: string;
  recommendation: string;
  source: ResearchSource;
}

export interface CodebaseContextEntry {
  file_path: string;
  description: string;
}

export interface ResearchOutput {
  topic: string;
  questions_and_answers: QuestionAnswer[];
  competitive_solutions: CompetitiveSolution[];
  technology_evaluations: TechnologyEvaluation[];
  codebase_context: CodebaseContextEntry[];
  risks_and_concerns: string[];
}

// --- Enriched Brief Sections (FR-010) ---

export interface ResearchFindings {
  competitive_landscape: CompetitiveSolution[];
  analogous_solutions: CompetitiveSolution[];
  technology_feasibility: TechnologyEvaluation[];
}

export interface RiskAssessment {
  risk: string;
  likelihood: "low" | "medium" | "high";
  impact: "low" | "medium" | "high";
  source: ResearchSource | null;
}

export interface TechnicalFeasibility {
  item: string;
  status: "confirmed_feasible" | "needs_validation";
  evidence: string;
  source: ResearchSource | null;
}

export interface EnrichedBriefSections {
  research_findings: ResearchFindings;
  risk_assessment: RiskAssessment[];
  technical_feasibility: TechnicalFeasibility[];
}
